name_rank_new:
    path:   /newname
    defaults: { _controller: NameRankBundle:Default:new }

name_rank_names:
    path:   /names
    defaults: { _controller: NameRankBundle:Default:listNames }

name_rank_compare:
    path:   /compare
    defaults: { _controller: NameRankBundle:Default:compareNames }

name_rank_home:
    path: /
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: name_rank_compare
        permanent: false